### ISSUE TITLE
[Enhancement] Create a page consisting of hosts that lack a hostname (ie hosts that aren't up).

### ISSUE THREAD

**Issue by PolyatomicBrian** [clayball/nector#20]
Perhaps have a table that shows the hosts' statuses today, and the hosts' statuses yesterday? This way the user can see if any of the hosts went down the day before. Or just a chart of hosts that say "Host [host] is currently [up/down], and was last [down/up] on [date]."?

You're more creative than I am, so I'll leave the decision to you, @clayball, haha.

Both will require the nightly scans, which we can (hopefully) start soon.

**Comment by clayball** [comment]
Adding something to the Host details page such as ```Status: [up, offline (last seen)]``` might be useful.

Lets leave this be for now.

**Comment by PolyatomicBrian** [comment]
Fixed in merge #33
