### ISSUE TITLE
[Suggestion] Provide sample files: hosts.xml and subnets.txt

### ISSUE THREAD

**Issue by PolyatomicBrian** [clayball/nector#4]
import-hosts.py is currently catered toward the semantics used in our hosts.xml and subnets.txt.
To prevent any outside-users from bashing their heads in due to confusion, some sample files may prove helpful.

Does this sound like a good idea for the future?

**Comment by clayball** [comment]
I was just thinking about this this morning. It would be great if we could provide sample data so anyone can clone the repo and setup an example instance to see how things look and work.

Definitely a good idea!

Along the same lines, I was considering that our use will require certain a certain model. However, other may wish to implement their own model, i.e., custom db fields for hosts, subnets, etc. So, perhaps we could develop a mechanism to allow this type of flexibility. Maybe a script that asks questions and generates a config file (that can also be edited manually) or models.py file. We can tackles these questions after we add more functionality to the project.

**Comment by clayball** [comment]
Posting a few thoughts here so I won't forget :)

- We can include a basic model. The example data could use this model. (can do this now)
- We can include our model for a more robust implementation. (this is a WIP)
- We can include a custom model generator. (future work)

**Comment by PolyatomicBrian** [comment]
Just submitted a new pull request that contains sample files.
The naming conventions are a little annoying (the user has to rename _sample-hosts.xml_ to _hosts.xml_), but this prevents conflicts with our .gitignore. We can leave it as is, or think of a better alternative in the future.
